import { Assessment } from '../types/assessment'

export const pcl5Assessment: Assessment = {
  id: "pcl5",
  title: "PCL-5 - Sàng lọc PTSD",
  description: "Thang đo rối loạn căng thẳng sau sang chấn tâm lý trong 1 tháng qua",
  questions: [
    {
      id: "pcl5-1",
      text: "Những ký ức, suy nghĩ, hoặc hình ảnh không mong muốn về sự kiện căng thẳng đó?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-2",
      text: "Những giấc mơ gây khó chịu về sự kiện đó?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-3",
      text: "Cảm giác như thể sự kiện đó đang xảy ra một lần nữa (hồi tưởng)?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-4",
      text: "Cảm thấy rất buồn bã, khó chịu khi có điều gì đó gợi nhớ về sự kiện?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-5",
      text: "Có những phản ứng mạnh mẽ về thể chất khi có điều gì đó gợi nhớ về sự kiện (tim đập nhanh, khó thở, đổ mồ hôi)?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-6",
      text: "Tránh né những ký ức, suy nghĩ, hoặc cảm xúc liên quan đến sự kiện?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-7",
      text: "Tránh né những hoạt động bên ngoài, địa điểm, con người, hoặc tình huống gợi nhớ về sự kiện?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-8",
      text: "Gặp khó khăn trong việc nhớ lại những phần quan trọng của sự kiện?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-9",
      text: "Có những niềm tin tiêu cực mạnh mẽ về bản thân, người khác, hoặc thế giới?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-10",
      text: "Đổ lỗi cho bản thân hoặc người khác về sự kiện hoặc những gì xảy ra sau đó?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-11",
      text: "Có những cảm xúc tiêu cực mạnh mẽ như sợ hãi, kinh hoàng, tức giận, tội lỗi, hoặc xấu hổ?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-12",
      text: "Mất hứng thú với những hoạt động mà bạn từng thích?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-13",
      text: "Cảm thấy xa cách hoặc cắt đứt với người khác?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-14",
      text: "Gặp khó khăn trong việc trải nghiệm những cảm xúc tích cực?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-15",
      text: "Hành vi khích động hoặc tự hủy hoại?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-16",
      text: "Quá cảnh giác hoặc luôn đề phòng nguy hiểm?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-17",
      text: "Dễ giật mình hoặc bị làm cho sợ hãi?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-18",
      text: "Gặp vấn đề về tập trung?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-19",
      text: "Gặp khó khăn khi đi ngủ hoặc ngủ không yên giấc?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
    {
      id: "pcl5-20",
      text: "Cảm thấy cáu kỉnh hoặc có những cơn giận dữ?",
      options: [
        { value: "0", label: "Không hề", score: 0 },
        { value: "1", label: "Một chút", score: 1 },
        { value: "2", label: "Vừa phải", score: 2 },
        { value: "3", label: "Khá nhiều", score: 3 },
        { value: "4", label: "Cực kỳ", score: 4 },
      ],
    },
  ],
  interpretation: [
    {
      min: 0,
      max: 32,
      level: "Thấp",
      description: "Mức độ triệu chứng PTSD thấp",
      recommendations: ["Duy trì hoạt động xã hội", "Thực hành kỹ thuật thư giãn", "Tập thể dục đều đặn"],
    },
    {
      min: 33,
      max: 37,
      level: "Ngưỡng",
      description: "Có thể có PTSD - cần đánh giá thêm",
      recommendations: ["Tham khảo chuyên gia tâm lý", "Theo dõi triệu chứng", "Tìm hiểu về liệu pháp PTSD"],
    },
    {
      min: 38,
      max: 80,
      level: "Cao",
      description: "Có khả năng cao mắc PTSD",
      recommendations: ["Cần gặp bác sĩ tâm thần ngay", "Liệu pháp chuyên biệt cho PTSD", "Hỗ trợ từ gia đình và bạn bè"],
    },
  ],
}